<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="CIPL1017-QA" failures="2" tests="2" name="pages" time="107.493" errors="0" timestamp="2022-09-23T12:53:42 IST">
  <testcase classname="pages.HomePage" name="FP01" time="3.539">
    <failure type="java.lang.AssertionError" message="Test case failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test case failed expected [true] but found [false]
at pages.HomePage.FP01(HomePage.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- FP01 -->
  <testcase classname="pages.HomePage" name="FP01" time="106.989">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)&amp;quot; because &amp;quot;this.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.relevantcodes.extentreports.ExtentTest.log(com.relevantcodes.extentreports.LogStatus, String)" because "this.test" is null
at core.WebEventListener.onTestFailure(WebEventListener.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- FP01 -->
  <testcase classname="pages.HomePage" name="FP03" time="0.0">
    <ignored/>
  </testcase> <!-- FP03 -->
</testsuite> <!-- pages -->
